djangocrud/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [    
               path('admin/', admin.site.urls),
               path('', include('tasks.urls', namespace="hello_app"))
               ]

tasks/urls.py
from django.urls import path
from .views import home, signup, tasks, signout, signin, create_task, task_detail, complete_task, delete_task, tasks_completed
app_name='hello_app'



urlpatterns = [
    path('', home, name="home"),
    path('signup/', signup, name="signup"), #esta ruta signup/ es la que se envia en el action del formulario y se recibe en el request
    path('tasks/', tasks, name="tasks"),
    path('logout/', signout, name="logout"),
    path('signin/', signin, name="signin"),
    path('create/task/', create_task, name="create_tasks"),
    path("tasks/<int:task_id>", task_detail, name="task_detail"), #con <> le pasamos un parametro al metodo task_detail en este caso el id
    path("tasks/<int:task_id>/complete", complete_task, name="complete_task"), #esto es para marcar las tareas completadas
    path("tasks/<int:task_id>/delete", delete_task, name="delete_task"), #esto es  para eliminar las tareas
    path("tasks_completed", tasks_completed, name="tasks_completed"), #eto es para realizar una lista de tareas completadas
    
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title + '- by '+ self.user.username

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task #el formulario se basara en este modelo task
        fields = ["title", "description", "important"] #estos seran los campos de los formularios a enviar
        widgets = {
            "title": forms.TextInput(attrs={'class': 'form-control', "placeholder": "Wirte a title"}),
            "description": forms.Textarea(attrs={'class': 'form-control', "placeholder": "Write a description"}),
            "important": forms.CheckboxInput(attrs={'class': 'form-check-input m-auto'})
        }

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # UserCreationForm me devuelve un formulario para crear un usuario, AuthenticationForm es para iniciar sesion con un usuario ya guardado
from django.http import HttpResponse
from django.contrib.auth.models import User 
from django.contrib.auth import login, logout, authenticate #el login crea la cookie para autenticar el usuario, el authenticated me irve para saber si el usuario se guardo o esta autenticado en la base de datos
from django.db import IntegrityError
from .forms import TaskForm
from .models import Task
from django.utils import timezone
from django.contrib.auth.decorators import login_required #esto es para proteger las rutas

# Create your views here.

# def helloworld(request):
#     title = "Hello World"
#     return render(request, 'signup.html', {
#         "form": UserCreationForm
#     })
    
def home(request):
    title = "Hello World"
    return render(request, 'tasks/home.html')



def signup(request): #registro de usuarios
    
    if request.method == "GET": #mostrar informacion en pantalla
        # print("enviando formulario")
        return render(request, 'tasks/signup.html', {
        "form": UserCreationForm
    })
    else:
        if request.POST["password1"] == request.POST["password2"]:  #con el post se recibe los datos del formulario y se procede a crear al usuario en la DB
            #register user
            try:
                user=User.objects.create_user(username=request.POST["username"], password=request.POST["password1"]) #se crea el usuario en la base de datos en la tabla user
                user.save()
                # return HttpResponse("User created succesfully")
                login(request, user) #el login crea la cookie para autenticar el usuario
                return redirect('hello_app:tasks') #hay que colocarle el nombre de la app de las urls para que pueda redireccionar
            
            except IntegrityError:
                return render(request, 'tasks/signup.html', { #si el usuario ya existe te quedas en ese mismo render con la misma ruta pero le envias el error de que ya existe el usuario
                    "form": UserCreationForm,
                    "error": "Username already exists"
                })
           
        return render(request, 'tasks/signup.html', {
                    "form": UserCreationForm,
                    "error": "password do no match"
                })
            
            
            
        # print(request.POST) #se ven los datos que el cliente envia
        # print("obteniendo datos")
        

@login_required #este decorador es para proteger las rutas
def tasks(request):
    print(request)
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=True) #vas a traer las que estan vacias, sirve para mostrar al usuario los que le faltan hacer
    return render(request, "tasks/tasks.html", {"tasks": tasks, "task_pending":True})

def signout(request): #esto cierra la sesion
    logout(request)
    return redirect("hello_app:home")

def signin(request):
    if request.method == "GET": #si e get quiere decir que va a renderizar, no va a mandar la informacion
         return render(request, "tasks/signin.html", {
            "form": AuthenticationForm   #esto añade el formulario para iniciar sesion que ya te permite autenticar
        })
    else: #aqui es POST por ende se envia los datos
        user=authenticate(request, username=request.POST["username"], password=request.POST["password"]) #va a verificar si el usuario esta en la DB
        if user is None: #si no encuentra el usuario en la base de datos entonces mandas un error y renderizas signin.html
            return render(request, "tasks/signin.html", {
                "form": AuthenticationForm,
                'error': "Username or password is incorrect"
            })
        else: #si si encontro el usuario 
            login(request, user) #guarda la sesion iniciada
            return redirect("hello_app:tasks")
        
#CRUD

#CREATE 

@login_required
def create_task(request):
    
    if request.method == "GET":
        return render(request, "tasks/create_task.html", {
        "form": TaskForm
    })
    else: 
        try:
            form=TaskForm(request.POST)
            new_task = form.save(commit=False) #esto es para que no me guarde los datos si no que lo envie y los muestra
            new_task.user = request.user #trae al usuario de la tarea que eta registrado
            new_task.save() #aqui si guarda el formulario
            print(form) #trae la informacion enviada en el formulario
            return redirect("hello_app:tasks")
        except ValueError:
               return render(request, "tasks/create_task.html", {
                "form": TaskForm,
                "error": "Please provide valid data"
                        })
#READ (GET) y UPDATE

@login_required
def task_detail(request, task_id):
    if request.method == "GET":
        print(task_id)
        task=get_object_or_404(Task, pk=task_id, user=request.user)
        form = TaskForm(instance=task) #me llena el formulario con los datos del task, esto es para poder actualizar
        return render(request, "tasks/task_detail.html", {"task": task, "form": form})
    else:
        try:
            print(request.POST) #me trae la informacion que colocamos en el formulario
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            form = TaskForm(request.POST, instance=task) #aqui guardamos la nueva informacion que colocamos en el formulario
            form.save()
            return redirect("hello_app:tasks")
        except ValueError:
              return render(request, "tasks/task_detail.html", {"task": task, "form": form, "error":"Error updating task"})
          
#COMPLETED

@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == "POST":
        task.datecompleted = timezone.now() #cambia la fecha a la fecha completada
        task.save()
        return redirect("hello_app:tasks")
    
#DELETE

@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == "POST":
        task.delete()
        return redirect("hello_app:tasks")
    
#listar tarea completadas

@login_required
def tasks_completed(request):
    print(request)
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted') #vas a traer las tareas que tienen una fecha completada y ordenarla
    return render(request, "tasks/tasks.html", {"tasks": tasks})

    
    
            
            
                
            
    
            
            
       
   
    
   
    

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <title>Django CRUD Application</title>
</head>
<body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Django App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li  class="nav-item">
                    <a href="/" class="nav-link">Home</a>
                </li>
                
                {% if user.is_authenticated %} <!--esto sirve para verificar si el usuario esta autenticado, si lo esta muestra el logout y si no el signup-->
                <li  class="nav-item">
                    <a  class="nav-link" href="{% url 'hello_app:tasks' %}">Tasks pending</a> <!--es mejor usar esta forma de colocar las url-->
                </li>
                <li  class="nav-item">
                    <a  class="nav-link"  href="{% url 'hello_app:tasks_completed' %}">Tasks completed</a>
                </li>
                <li  class="nav-item">
                    <a  class="nav-link" href="/create/task">Create Task</a>
                </li  class="nav-item">
                <li  class="nav-item">
                    <a  class="nav-link"  href="/logout">Logout</a>
                </li>
                {% else %}
                <li  class="nav-item">
                    <a  class="nav-link" href="/signup">Signup</a>
                </li>
                <li  class="nav-item">
                    <a  class="nav-link" href="/signin">Signin</a>
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    
    {% endblock %}

</body>
</html>

tasks/templates/tasks/create_task.html
{% extends "tasks/base.html" %}

{% block content %}

<main class="container">
    <div class="row">

        <div class="col-md-4 offset-md-4 mt-5">
           
            <form action="/create/task/" method="POST" class="card card-body">
                    <h1>Create Task</h1>
                    {{error}}
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary">
                        Save
                    </button>
        
            </form>
        </div>
    </div>
</main>

{% endblock %}

tasks/templates/tasks/home.html
{% extends "tasks/base.html" %}


{% block content %}



    <main class="container py-5">
        <section class="card card-body">
            <h1 class="display-1 text-center">Django App</h1>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. 
                Voluptate cum nam sunt fugiat fugit non ratione esse, 
                consectetur consequatur officia veritatis ex, 
                adipisci quasi iusto vitae cumque at vel ipsam iste. 
                Sunt aliquid vitae maxime officia nam quas dolores dicta expedita ex, 
                ipsa dolor ratione mollitia reprehenderit, 
                recusandae laudantium earum minus esse quod qui obcaecati cupiditate deleniti! Explicabo, 
                soluta sunt quod perferendis ipsa voluptates unde vero est quas dolores quo expedita deserunt optio earum dolorum maxime non delectus sequi, 
                blanditiis eveniet sed, molestiae ullam. 
                Reprehenderit error doloribus labore odit provident accusantium inventore nam laborum temporibus dolore 
                quibusdam, voluptas ducimus magnam.</p>

                <div class="text-center">
                    <a class="btn btn-secondary" href="/signin/">
                        Signin
                    </a>
                    <a class="btn btn-dark" href="/signup">
                        Signup
                    </a>
                </div>
              

        </section>
    </main>
    
    
{% endblock %}

tasks/templates/tasks/signin.html
{% extends "tasks/base.html" %}

{% block content %}
 
<main class="container">
    <div class="row">
        <section class="col-md-4 offset-md-4 mt-5">
            <form action="/signin/" method="POST" class="card card-body">
              
                <h1 class="text-center">Signin</h1>
                {{error}}
                {% csrf_token %} <!--eto sirve para mostrar el token del formulario para evitar falsificaciones del formularios-->
                
                <!-- {{form}} el as_p en el formulario ordena mejor el formulario -->
                <div class="mb-3">
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="Write your username">
                </div>
        
                <div class="mb-3">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Write your password">
                </div>
        
           
                <button class="btn btn-primary">
                    Signin
                </button>
            </form>
           </section>
    </div>
    
</main>
   
   

{% endblock %}

tasks/templates/tasks/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'tasks/base.html' %}

    {% block content %}

   <main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form action="/signup/" method="POST" class="card card-body mt-5"> <!--el action e para enviar la info del formulario, va a buscar una ruta llamada signup, el method e importante para que no e vea en la url los datos del user-->

                <h1 class="text-center">SING UP</h1>
                {{error}}
                {% csrf_token %} <!--eto sirve para mostrar el token del formulario para evitar falsificaciones del formularios-->
                
                <!-- {{form}} el as_p en el formulario ordena mejor el formulario -->
                <div class="mb-3">
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="Write your username">
                </div>

                <div class="mb-3">
                    <label for="password1">Password:</label>
                    <input type="password" name="password1" id="password1" class="form-control" placeholder="Write your password">
                </div>

                <div class="mb-3">
                    <label for="password2">Confirm your password:</label>
                    <input type="password" name="password2" id="password2" class="form-control" placeholder="Confirm your password">
                </div>

                <button class="btn btn-primary">
                    signup
                </button>
            </form>
        </div>
    </div>
   </main>
   
   

    {% endblock %}
    
</body>
</html>

tasks/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}

{% block content %}
   
   
   <main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            
    <h1 class="text-secondary">{{task.title}}</h1>

            {{error}}
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">
                    Update
                </button>
        
            </form>
            <div class="mt-5 d-flex">
               
            
                <form action="{% url 'hello_app:complete_task' task.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-secondary">
                        Complete
                    </button>
                </form>
                <form action="{% url 'hello_app:delete_task' task.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger">
                        DELETE
                    </button>
                </form>
            </div>

    
        </div>
    </div>
   </main>
   

{% endblock %}

tasks/templates/tasks/tasks.html
{% extends 'tasks/base.html' %} {% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

        {% if task_pending%}
            <h1 class="text-center display-3 py-5">Pending Tasks</h1>
        {% else %}
            <h1 class="text-center display-3 py-5">Completed Tasks</h1>
        {% endif %}
     



        

  
      <ul class="list-group">
        {% for task in tasks %}
        <a
          class="list-group-item"
          href="{% url 'hello_app:task_detail' task.id %}"
        >
          <!--lo cuando le damos click a cada task te redirecciona a task_detail para mostrar los detalles de cada task pero segun el id -->
          <header class="d-flex justify-content-between">
            {% if task.important %}

            <h1 class="fw-bold text-success">{{task.title}}</h1>

            {% else %}

            <h1 class="fw-bold">{{task.title}}</h1>
            {% endif %}
            <p>{{task.user.username}}</p>
          </header>
          <p>{{task.description}}</p>

          <p>{{ task.datecompleted|date:"M j Y H:i" }}</p>
        </a>
        {% endfor %}
      </ul>
    </div>
  </div>
</main>

{% endblock %}